### PR TITLE
Update NSIS script (text string multilanguage)

### PR DESCRIPTION
**Pull request by bovirus**
Modified QEMU NSIS script to sue variable instead hard-coded text
Add two external language files (for now English & Italian) to translate the strings.

@stweil 
Please check and if it's OK merge to your repositories.
If it's OK please merge it on QEMU official repository.
Thanks.

### CODE REVIEW

**Comment by bovirus** [comment]
@stweil 

Sorry but I didn't understand.
Is this latest PR OK?

**Comment by stweil** [comment]
I hope so, but I still have to test it.

**Comment by bovirus** [comment]
OK: Thanks.

I just want to confirm that latest is the version that you will use and delete/close the other PR. ;-)

**Comment by stweil** [comment]
The build fails with this patch:

    $ makensis -V2 -NOCD -DW64 \
    >                 -DCONFIG_DOCUMENTATION="y" \
    >                 -DCONFIG_GTK="y" \
    >                 -DBINDIR="/tmp/qemu-nsis" \
    >                 -DDLLDIR="/qemu/dll/w64" \
    >                 -DSRCDIR="/qemu" \
    >                 -DOUTFILE="qemu-setup-4.0.91.exe" \
    >                 -DDISPLAYVERSION="4.0.91" \
    >                 /home/stefan/src/qemu/repo.or.cz/qemu/ar7/qemu.nsi
    !include: could not find: "installer\installer_strings_english.nsh"
    Error in script "/qemu/qemu.nsi" on line 115 -- aborting creation process

**Comment by stweil** [comment]
When I fix the include path for `installer_strings_english.nsh`, I get these warnings:

    warning 6000: unknown variable/constant "{Tools_Section_Text}" detected, ignoring (/qemu/qemu.nsi:173)
    warning 6000: unknown variable/constant "{System_Emulations_Section_Text}" detected, ignoring (/qemu/qemu.nsi:181)
    warning 6000: unknown variable/constant "{Desktop_icons_Text}" detected, ignoring (/qemu/qemu.nsi:187)
    warning 6000: unknown variable/constant "{Libraries_DLL_Section_Text}" detected, ignoring (/qemu/qemu.nsi:197)
    warning 6000: unknown variable/constant "{Documentation_Section_Text}" detected, ignoring (/qemu/qemu.nsi:204)
    warning 6000: unknown variable/constant "{User_Documentation_Link_Text}" detected, ignoring (/qemu/qemu.nsi:208)
    warning 6000: unknown variable/constant "{Start_Menu_Shortcuts_Section_Text}" detected, ignoring (/qemu/qemu.nsi:213)
    warning 6000: unknown variable/constant "{Uninstall_Link_Text}" detected, ignoring (/qemu/qemu.nsi:215)
    warning 6000: unknown variable/constant "{Uninstall_Section_Text}" detected, ignoring (/qemu/qemu.nsi:222)
    warning 6000: unknown variable/constant "{User_Documentation_Link_Text}" detected, ignoring (/qemu/qemu.nsi:231)
    warning 6000: unknown variable/constant "{Technical_Documentation_Link_Text}" detected, ignoring (/qemu/qemu.nsi:232)
    warning 6000: unknown variable/constant "{Uninstall_Link_Text}" detected, ignoring (/qemu/qemu.nsi:233)
    warning 6000: unknown variable/constant "{GNOME_desktop_icon_theme_Section_Text}" detected, ignoring (macro:MUI_DESCRIPTION_TEXT:8)
    warning 6000: unknown variable/constant "{System_Emulations_Section_Text}" detected, ignoring (macro:MUI_DESCRIPTION_TEXT:8)
    warning 6000: unknown variable/constant "{Alpha_system_emulation_Section_Text}" detected, ignoring (macro:MUI_DESCRIPTION_TEXT:8)
    warning 6000: unknown variable/constant "{PC_i386_system_emulation_Section_Text}" detected, ignoring (macro:MUI_DESCRIPTION_TEXT:8)
    warning 6000: unknown variable/constant "{Tools_Section_Text}" detected, ignoring (macro:MUI_DESCRIPTION_TEXT:8)
    warning 6000: unknown variable/constant "{Libraries_DLL_Section_Text}" detected, ignoring (macro:MUI_DESCRIPTION_TEXT:8)
    warning 6000: unknown variable/constant "{Documentation_Section_Text}" detected, ignoring (macro:MUI_DESCRIPTION_TEXT:8)
    warning 6000: unknown variable/constant "{Menu_entries_Section_Text}" detected, ignoring (macro:MUI_DESCRIPTION_TEXT:8)

**Comment by bovirus** [comment]
@stweil 

I tested it with NSIS under Windows and my files are for me were seems ok.
But probbaly the problem is use of "\" that it's OK for Windows but nor for Linux.

How can fix the path in your script?
Please make a small change. Move two files

**_installer_strings_english.nsh
installer_strings_italian.nsh_**

in the root and change in **_qemu.nsi_**

**_!include installer\installer_strings_english.nsh
!include installer\installer_strings_italian.nsh_**

as

**_!include installer_strings_english.nsh
!include installer_strings_italian.nsh_**

If youw ant we can test it a separate branch

Please tell me something about your software environment to enable me to make a similar system to test

NSIS version
OS version
If OS is Linux pelase tell me something more.

**Comment by stweil** [comment]
As I wrote above, I could fix the include statements, but there remain the unknown variables. That creates an installer which is unusable.

**Comment by bovirus** [comment]
@stweil 

There is something different from your configuration and my configuration.
And I didn't understand why.

Because in My configuration it didn't report any error about localization.

I have Windows 7 64bit & NSIS 3.04

I cloned your repository.
The I replace the file in my PR.

I ran NSIS 3.04 and load QEMU.NSI.
Then the report about compilation is this the log

https://mega.nz/#!qE51UYQJ!qcOyREqpVv0N8pybat5PoTXMgwpyVRfyvk4Qb5XRdEU

You got an error not but AFTER loading localization (without error) regarding some file missing in sources.
 
Could you create a test-branch where we can test it?

Could you please make a zip of your compilation folder with all files and uplaod it on some host to enable me to download and test it?

**Comment by stweil** [comment]
See the complete [output from `makensis`](https://qemu.weilnetz.de/test/makensis.log).

**Comment by stweil** [comment]
The branch [nsis-test](https://github.com/stweil/qemu/tree/nsis-test) should allow a local test without requiring any build artifacts.

**Comment by stweil** [comment]
This PR was superseded by #6, so closing it.

**Pull request closed without merging**
