### PR TITLE
Update multi-language script (fixed)

### PR DESCRIPTION
**Pull request by bovirus**

### CODE REVIEW

**Comment by bovirus** [comment]
@stweil

Could you please check, include these changes and try to build  a new multi-langauge installer?

**Comment by stweil** [comment]
I just merged your commit and saw that you did neither set your author name nor your e-mail address. Was that intentional, or do you want to fix this, so git shows the correct information in the history? You can also send me the information, then I'd fix it in git.

**Comment by bovirus** [comment]
@stweil

Sorry but I didn't post them because I beleive that was just a test.
These are my data

Nick = bovirus
Email = bovirus at gmail.com (I used my email here in this mofe to avoid automatic catching by internet).
 
I downlaod the new installer from here

https://qemu.weilnetz.de/w64/qemu-w64-setup-20190712.exe

I checked that now are available in 4 languages: English/French/German/Italian. Good.
The installer window are all fully localized (for Italian).

I have already the QEMU installed.
Then I re-install it with new iinstalelr version (multilanguage) and I checked that the new installer seems didn't create QEMU program group.
Could you check pelase?

**Comment by stweil** [comment]
The new installer does not work. This might be caused by wrong use of the new localized strings. I think that NSIS expects `${NAME}` instead of `$(NAME)`.

Do you want to use a nick name in the commit history? The QEMU contribution guidelines require a real name, so I could never send your contribution to the mainstream QEMU.

**Comment by bovirus** [comment]
Yes.
The strings hould be used with ${xxx}-
For my name please use "Roberto B:".

I propose an imporvemnts.

Instead to make all changes in qemu.nsi you can do in this way

Create a 

**_installarer_** 

sub-folder . Then create n files ex.

**_installer_strings_english.nsh
installer_strings_french.nsh
installer_strings_german.nsh
installer_strings_italian.nsh_**

then in qemu could add 

**_!include installer\installer_strings_english.nsh
!include installer\installer_strings_french.nsh
!include installer\installer_strings_german.nsh
!include installer\installer_strings_italian.nsh_**

In this way is more flexible and anyone that want to add other langauge add a separate installer language file and relative !include in qemu.nsi.

What do you think about it?

**Comment by bovirus** [comment]
Could please rejct my prosal.
I will investigating about it.

What version of NSIS are you using?

**Comment by stweil** [comment]
I am using https://packages.debian.org/buster/nsis (3.04-1). The latest installer supports Italian and Spanish at least for the standard texts.

**Pull request merged**
